### ISSUE TITLE
pomogite :)

### ISSUE THREAD

**Issue by vvwvvvvvwvvvvvvw** [mxnster/sui-testnet-nft-bot#2]
<img width="397" alt="Снимок экрана 2022-11-16 в 05 22 06" src="https://user-images.githubusercontent.com/104582637/202067895-5a9e3409-a3c1-4b6e-8659-b357cbcf09b5.png">

**Comment by waxanator** [comment]
<img width="571" alt="Снимок экрана 2022-11-16 в 05 28 40" src="https://user-images.githubusercontent.com/104582637/202068851-6109a272-dd93-4218-a28a-f6ad93f32f20.png">

GENII

**Comment by vvwvvvvvwvvvvvvw** [comment]
<img width="499" alt="Снимок экрана 2022-11-16 в 05 29 53" src="https://user-images.githubusercontent.com/104582637/202068998-e53a000c-4045-46d6-bf2c-23d48db2d9f7.png">

разобрался, все работает, спасибо :) остается надеяться что в коде ничего такого не написано... :)

**Comment by vvwvvvvvwvvvvvvw** [comment]
а можно как-то сделать так чтобы повторно не создавался кошелек с одной и той же прокси?

**Comment by mxnster** [comment]
> а можно как-то сделать так чтобы повторно не создавался кошелек с одной и той же прокси?

Убрать цикл while

**Comment by sashamaxymchuk** [comment]
> <img alt="Снимок экрана 2022-11-16 в 05 29 53" width="499" src="https://user-images.githubusercontent.com/104582637/202068998-e53a000c-4045-46d6-bf2c-23d48db2d9f7.png">
> 
> разобрался, все работает, спасибо :) остается надеяться что в коде ничего такого не написано... :)

в чём была проблемма? а то у меня такая же. В самом прокси?
